### ISSUE TITLE
Requirement cspicer/ansible-supervisor doesn't exist

### ISSUE THREAD

**Issue by sammcj** [cspicer/ansible-docker#2]
https://github.com/cspicer/ansible-docker/blob/master/requirements.yml#L5

**Comment by cspicer** [comment]
Hello,

Thanks for reporting this, and I'm sorry for the extremely late response – I somehow overlooked this thread. I'm not sure if you still have any interest in the role, but this dependency was removed some time ago and should no longer be causing issues.

Thanks again for taking the time to report this issue. I'm going to close it now given the amount of time that's passed, but feel free to comment if you're still having trouble and I can re-open.
